name: Run Pytest on Push

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xml

      - name: Run tests and generate XML report
        run: pytest tests/stub_tests.py --junitxml=pytest-report.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: pytest-report.xml
